### ISSUE TITLE
Segfault for lb cpu + lbboundaries for agrid incompatible to local box_l

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#1784]
Probably a call of handle_errors() in system.actors.add()

**Comment by hmenke** [comment]
Cannot reproduce with `HEAD` at 5f8d0b3b27c72aec77a69ceae0c4d17f75ac8f51
```python
import espressomd
import espressomd.lb as lb

system = espressomd.System()
system.box_l = [1,1,1]
system.time_step = 0.01
system.cell_system.skin = 0.1

lbm = lb.LBFluid(agrid=2,dens=1,visc=1,fric=1,tau=system.time_step)
system.actors.add(lbm)

system.integrator.run(0)
```
This gives a clean error and throws an exception.
```
$ ./pypresso test.py 
ERROR: Lattice spacing agrid[0]=2 is incompatible with local_box_l[0]=1 ( box_l[0]=1 node_grid[0]=1 )
ERROR: Lattice spacing agrid[1]=2 is incompatible with local_box_l[1]=1 ( box_l[1]=1 node_grid[1]=1 )
ERROR: Lattice spacing agrid[2]=2 is incompatible with local_box_l[2]=1 ( box_l[2]=1 node_grid[2]=1 )
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    system.integrator.run(0)
  File "espressomd/integrate.pyx", line 63, in espressomd.integrate.Integrator.run (/tmp/espresso/python/build/src/python/espressomd/integrate.cpp:1553)
  File "espressomd/utils.pyx", line 268, in espressomd.utils.handle_errors (/tmp/espresso/python/build/src/python/espressomd/utils.cpp:6995)
Exception: Encoutered errors during integrate
```

**Comment by RudolfWeeber** [comment]
On Thu, Jan 25, 2018 at 08:15:14PM +0000, Henri Menke wrote:
> Cannot reproduce on 5f8d0b3b27c72aec77a69ceae0c4d17f75ac8f51
> ```python
> import espressomd
> import espressomd.lb as lb
> 
> system = espressomd.System()
> system.box_l = [1,1,1]
> system.time_step = 0.01
> system.cell_system.skin = 0.1
> 
> lbm = lb.LBFluid(agrid=2,dens=1,visc=1,fric=1,tau=system.time_step)
> system.actors.add(lbm)
> 
> system.integrator.run(0)
Try adding boundaries before the integrator.run() call on 2 mpi
tasks. Then, then lbfluid[] on the 2nd task is not initialized and
setting lbfluid[].boundary segfaults.

**Comment by hmenke** [comment]
Okay, now I can reproduce.
```python
import espressomd
from espressomd import lb
from espressomd import lbboundaries
from espressomd import shapes

system = espressomd.System()
system.box_l = [1,1,1]
system.time_step = 0.01
system.cell_system.skin = 0.1

lbm = lb.LBFluid(agrid=2,dens=1,visc=1,fric=1,tau=system.time_step)
system.actors.add(lbm)

wall = lbboundaries.LBBoundary(shape=shapes.Wall(normal=[0,0,1],dist=0.5))
system.lbboundaries.add(wall)

system.integrator.run(0)
```
Backtrace
```
#0  0x00007fffed420189 in LBBoundaries::lb_init_boundaries () at /tmp/espresso/python/src/core/lbboundaries.cpp:278
        n = 0
        node_domain_position = {0, 0, 0}
        offset = {0, 0, 0}
        the_boundary = -1
        x = 32767
        y = -161362586
        z = 32767
        pos = {6.9533480277050193e-310, 7.9050503334599447e-323, 6.9533558072808603e-310}
        dist = 0
        dist_tmp = 0
        dist_vec = {6.9533558072808603e-310, 6.9533478452322483e-310, 6.9533558072832318e-310}
        __PRETTY_FUNCTION__ = "void LBBoundaries::lb_init_boundaries()"
#1  0x00007ffff6648ce5 in ScriptInterface::LBBoundaries::LBBoundaries::add_in_core (this=0x29e07e0, obj_ptr=
    std::shared_ptr (count 3, weak 1) 0xa1ebe0) at /tmp/espresso/python/src/script_interface/lbboundaries/LBBoundaries.hpp:17
No locals.
#2  0x00007ffff664d5ab in ScriptInterface::ScriptObjectRegistry<ScriptInterface::LBBoundaries::LBBoundary>::call_method (this=0x29e07e0, 
    method="add", parameters=std::map with 1 element = {...})
    at /tmp/espresso/python/src/script_interface/ScriptObjectRegistry.hpp:41
        obj_ptr = std::shared_ptr (count 3, weak 1) 0xa1ebe0
#3  0x00007ffff66d0cb8 in ScriptInterface::ParallelScriptInterface::call_method (this=0x35a8e70, name="add", 
    parameters=std::map with 1 element = {...}) at /tmp/espresso/python/src/script_interface/ParallelScriptInterface.cpp:123
        p = std::map with 1 element = {["object"] = {which_ = 7, 
            storage_ = {<boost::detail::aligned_storage::aligned_storage_imp<32ul, 8ul>> = {data_ = {
                  buf = "\024\000\000\000\000\000\340?\003", '\000' <repeats 13 times>, "\360?\000\000\000\000\000\000\000", 
                  align_ = {<No data fields>}}}, static size = <optimized out>, static alignment = <optimized out>}}}
        d = {first = "add", second = std::map with 1 element = {["object"] = {which_ = 7, 
              storage_ = {<boost::detail::aligned_storage::aligned_storage_imp<32ul, 8ul>> = {data_ = {
                    buf = "\024\000\000\000\000\000\340?de_grid[2]=1 )\000\000 1\267\001\000\000\000", align_ = {<No data fields>}}}, 
                static size = <optimized out>, static alignment = <optimized out>}}}}
        ret = {which_ = -9568, storage_ = {<boost::detail::aligned_storage::aligned_storage_imp<32ul, 8ul>> = {data_ = {
                buf = "\340\026w\316\377\177\000\000\000*\303\350\377\177\000\000(\032w\316\377\177\000\000\000\233\267\001\000\000\000", 
                align_ = {<No data fields>}}}, static size = <optimized out>, static alignment = <optimized out>}}
#4  0x00007fffe89e42a5 in __pyx_pf_10espressomd_16script_interface_16PScriptInterface_12call_method (__pyx_v_self=0x7fffce7b5af0, 
    __pyx_v_method=0x7ffff7f890a8, __pyx_v_kwargs=0x7fffce7716e0)
    at /tmp/espresso/python/build/src/python/espressomd/script_interface.cpp:2623
        __pyx_v_parameters = std::map with 1 element = {["object"] = {which_ = 7, 
            storage_ = {<boost::detail::aligned_storage::aligned_storage_imp<32ul, 8ul>> = {data_ = {
                  buf = "\023\000\000\000\000\000\000\000XC\267\001\000\000\000\000XC\267\001\000\000\000\000\000\000ebcdic", 
                  align_ = {<No data fields>}}}, static size = <optimized out>, static alignment = <optimized out>}}}
        __pyx_v_name = 0x7ffff7fbac60
        __pyx_r = 0x0
        __pyx_t_1 = 0x0
        __pyx_t_2 = 9
        __pyx_t_3 = 1
        __pyx_t_4 = 1
        __pyx_t_5 = 0x0
        __pyx_t_6 = 0
        __pyx_t_7 = 0x0
        __pyx_t_8 = 0x0
        __pyx_t_9 = 0x0
        __pyx_t_10 = 0x0
        __pyx_t_11 = "add"
        __pyx_t_12 = {which_ = 0, storage_ = {<boost::detail::aligned_storage::aligned_storage_imp<32ul, 8ul>> = {data_ = {
                buf = "\026\\I\000\000\000\000\000\370\027w\316\377\177\000\000\343\266|\316\377\177\000\000\060\332\377\377\377\177\000", 
                align_ = {<No data fields>}}}, static size = <optimized out>, static alignment = <optimized out>}}
        __pyx_lineno = 0
        __pyx_filename = 0x0
        __pyx_clineno = 0
#5  0x00007fffe89e34c7 in __pyx_pw_10espressomd_16script_interface_16PScriptInterface_13call_method (__pyx_v_self=0x7fffce7b5af0, 
    __pyx_args=0x7fffce76f9d0, __pyx_kwds=0x7fffce771a28)
    at /tmp/espresso/python/build/src/python/espressomd/script_interface.cpp:2491
        __pyx_v_method = 0x7ffff7f890a8
        __pyx_v_kwargs = 0x7fffce7716e0
        __pyx_lineno = 0
        __pyx_filename = 0x0
        __pyx_clineno = 0
        __pyx_r = 0x0
#6  0x00000000004c37ed in PyEval_EvalFrameEx ()
No symbol table info available.
#7  0x00000000004b9ab6 in PyEval_EvalCodeEx ()
No symbol table info available.
#8  0x00000000004c1e6f in PyEval_EvalFrameEx ()
No symbol table info available.
#9  0x00000000004b9ab6 in PyEval_EvalCodeEx ()
No symbol table info available.
#10 0x00000000004eb30f in ?? ()
No symbol table info available.
#11 0x00000000004e5422 in PyRun_FileExFlags ()
No symbol table info available.
#12 0x00000000004e3cd6 in PyRun_SimpleFileExFlags ()
No symbol table info available.
#13 0x0000000000493ae2 in Py_Main ()
No symbol table info available.
#14 0x00007ffff7810830 in __libc_start_main (main=0x4934c0 <main>, argc=2, argv=0x7fffffffe198, init=<optimized out>, 
    fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe188) at ../csu/libc-start.c:291
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {0, 5805839480523786533, 4797376, 140737488347536, 0, 0, -5805839784654993115, 
                -5805822148616451803}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x2, 0x4934c0 <main>}, data = {prev = 0x0, 
              cleanup = 0x0, canceltype = 2}}}
        not_first_call = <optimized out>
#15 0x00000000004933e9 in _start ()
No symbol table info available.
```
