### ISSUE TITLE
Test `#67: coulomb_mixed_periodicity` fails when run in parallel (X>3 cores)

### ISSUE THREAD

**Issue by pkreissl** [espressomd/espresso#2061]
Test `#67: coulomb_mixed_periodicity` fails on with:
```
.ERROR: number of cells 3 is smaller than minimum 4 (interaction range too large or min_num_cells too large)
ERROR: number of cells 3 is smaller than minimum 4 (interaction range too large or min_num_cells too large)
ERROR: number of cells 3 is smaller than minimum 4 (interaction range too large or min_num_cells too large)
ERROR: number of cells 3 is smaller than minimum 4 (interaction range too large or min_num_cells too large)
E
======================================================================
ERROR: test_zz_p3mElc (__main__.CoulombMixedPeriodicity)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/pathtoespresso/build/testsuite/coulomb_mixed_periodicity.py", line 118, in test_zz_p3mElc
    self.S.actors.add(p3m)
  File "espressomd/actors.pyx", line 186, in espressomd.actors.Actors.add (/pathtoespresso/build/src/python/espressomd/actors.cpp:5237)
  File "espressomd/actors.pyx", line 49, in espressomd.actors.Actor._activate (/pathtoespresso/build/src/python/espressomd/actors.cpp:2009)
  File "espressomd/electrostatics.pyx", line 347, in espressomd.electrostatics.P3M._activate_method (/pathtoespresso/build/src/python/espressomd/electrostatics.cpp:5138)
  File "espressomd/electrostatics.pyx", line 338, in espressomd.electrostatics.P3M._tune (/pathtoespresso/build/src/python/espressomd/electrostatics.cpp:4910)
  File "espressomd/electrostatics.pxd", line 134, in espressomd.electrostatics.python_p3m_adaptive_tune (/pathtoespresso/build/src/python/espressomd/electrostatics.cpp:11013)
  File "espressomd/utils.pyx", line 268, in espressomd.utils.handle_errors (/pathtoespresso/build/src/python/espressomd/utils.cpp:7111)
Exception: Error in p3m_adaptive_tune
```
when run on more than three cores (checked up to 7 cores).

**Comment by RudolfWeeber** [comment]
The test saves a node grid at start and restores it for the p3m elc test, when it may no longer be feasable.

I don't think that should be done. Leaving that code out, one gets an error from p3m_init about the node grid having to be sorted. The test passes, if one does this.
This may be a regression from the min_num_cells change.

What would be the best way to proceed? @fweik
