### ISSUE TITLE
LB ckeckpoint error

### ISSUE THREAD

**Issue by iammmiru** [espressomd/espresso#2135]
While Espresso tries to load a checkpoint which includes lb_fluid as an actor, it produces the following error.
It happens if I use 'couple = '3pt'' feature. '2pt' does not make this error.

I also included a simple code that reproduces the error.
I don't know a nice way of putting my code here so I just did copy and past.

```
Traceback (most recent call last):
  File "lbfluid_checkpoint.py", line 21, in <module>
    checkpoint.load()
  File "/home/mlee/espresso/build/src/python/espressomd/checkpointing.py", line 227, in load
    checkpoint_data = pickle.load(f)
  File "espressomd/actors.pyx", line 22, in espressomd.actors.Actor.__setstate__ (/home/mlee/espresso/build/src/python/espressomd/actors.cpp:1320)
  File "espressomd/lb.pyx", line 140, in espressomd.lb.LBFluid._set_params_in_es_core (/home/mlee/espresso/build/src/python/espressomd/lb.cpp:3009)
  File "espressomd/lb.pxd", line 253, in espressomd.lb.python_lbfluid_set_couple_flag (/home/mlee/espresso/build/src/python/espressomd/lb.cpp:7957)
Exception: lb_lbfluid_set_couple_flag error at C-level interface
```

```python
from __future__ import print_function, division
from espressomd import System, lb, checkpointing
import numpy as np
import os


load_checkpoint = False
if os.path.isfile('lb_check.lbf'):
    load_checkpoint = True

checkpoint = checkpointing.Checkpoint(checkpoint_id =
                                         "checkpoint")
lbf_file_name = ('lb_check.lbf')

system = System(box_l = [10,10,10])
system.time_step = 1
system.cell_system.skin = 0.1

if load_checkpoint == True:
    print('load the checkpoint')
    checkpoint.load()
    system.actors.add(lbf)
    lbf.load_checkpoint(lbf_file_name,1)
    system.integrator.run(1, reuse_forces = True)
    while True:
        system.integrator.run(1000)
        checkpoint.save()
        lbf.save_checkpoint(lbf_file_name, 1)
        print('checkpoint')
    exit()

lbf = lb.LBFluidGPU(agrid=1.0, dens=1.0, visc=1.0, tau=1.0, fric = 1.0,
                    couple = '3pt')
system.actors.add(lbf)

checkpoint.register("lbf_file_name")
checkpoint.register("system.part")
checkpoint.register("system.time")
checkpoint.register("lbf")

while True:
    system.integrator.run(1000)
    checkpoint.save()
    lbf.save_checkpoint(lbf_file_name, 1)
    print('checkpoint')
```

**Comment by KaiSzuttor** [comment]
@fweik is 3pt coupling tested? IIRC its broken...

**Comment by fweik** [comment]
The actor in the script is a gpu lb, while the trace suggests that it is trying to create a CPU LB. The CPU LB does not support 3pt coupling, hence the error.
