### ISSUE TITLE
Problems installation

### ISSUE THREAD

**Issue by diogomusical** [espressomd/espresso#2532]
Good night,

I installed the espresso and start doing ./pypresso to do espressomd and the result: Traceback (latest last call):
File "<stdin>", line 1, under <module>
ImportError: No module named espressomd

And you do not have to solve this problem.
Thanks for the collaboration.

Diogo

**Comment by diogomusical** [comment]
Good afternoon,
input:
./pypresso
import espressomd

when does the code to input gives the following error:

import espressomd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named espressomd

Thank you
