### ISSUE TITLE
Problem installation

### ISSUE THREAD

**Issue by diogomusical** [espressomd/espresso#2560]
Hello,

input terminal:
./pypresso
import espressomd

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/diogo/Simulation/src/python/espressomd/__init__.py", line 23, in <module>
    import espressomd._init
ImportError: No module named _init

Thank you

**Comment by diogomusical** [comment]
Reinstall and compile.

Thank you
