### ISSUE TITLE
espresso-4.1.1: wang_landau_reaction_ensemble test fails on Fedora 31 under s390x

### ISSUE THREAD

**Issue by junghans** [espressomd/espresso#3305]
```
 37/144 Test #101: wang_landau_reaction_ensemble .....................***Failed    1.95 sec
Traceback (most recent call last):
  File "/builddir/build/BUILD/espresso/mpich/testsuite/python/wang_landau_reaction_ensemble.py", line 31, in <module>
    class ReactionEnsembleTest(ut.TestCase):
  File "/builddir/build/BUILD/espresso/mpich/testsuite/python/wang_landau_reaction_ensemble.py", line 81, in ReactionEnsembleTest
    np.savetxt("energy_boundaries.dat", np.c_[[0, 1], [0, 0], [9, 9]],
  File "/usr/lib64/python3.7/site-packages/numpy/lib/index_tricks.py", line 387, in __getitem__
    newobj = array(item, copy=False, subok=True, ndmin=ndmin)
ValueError: ndmin bigger than allowable number of dimensions NPY_MAXDIMS (=32)
```

Details [here] (https://github.com/espressomd/espresso/files/3844051/build_s390x.log.txt)

**Comment by mkuron** [comment]
That's pure Python code, so you should file a bug report against Fedora's s390x python package.
https://github.com/espressomd/espresso/blob/ef37a157aad3f62ce597bb73e169cfb026a42932/testsuite/python/wang_landau_reaction_ensemble.py#L80-L81

You could try changing `np.c_[[0, 1], [0, 0], [9, 9]]` to `np.transpose([[0, 1], [0, 0], [9, 9]])`. I've never seen `c_` before...

**Comment by junghans** [comment]
That help, I will make a PR, now the error is:
```
113/144 Test  #97: npt ...............................................***Failed   22.68 sec
1.9960783158287763 0.20572473188146218
.
----------------------------------------------------------------------
Ran 1 test in 15.117s
OK
--------------------------------------------------------------------------
mpiexec has exited due to process rank 1 with PID 0 on
node buildvm-s390x-17 exiting improperly. There are three reasons this could occur:
1. this process did not call "init" before exiting, but others in
the job did. This can cause a job to hang indefinitely while it waits
for all processes to call "init". By rule, if one process calls "init",
then ALL processes must call "init" prior to termination.
2. this process called "init", but exited without calling "finalize".
By rule, all processes that call "init" MUST call "finalize" prior to
exiting or it will be considered an "abnormal termination"
3. this process called "MPI_Abort" or "orte_abort" and the mca parameter
orte_create_session_dirs is set to false. In this case, the run-time cannot
detect that the abort call was an abnormal termination. Hence, the only
error message you will receive is this one.
This may have caused other processes in the application to be
terminated by signals sent by mpiexec (as reported here).
You can avoid this message by specifying -quiet on the mpiexec command line.
```

**Comment by mkuron** [comment]
Thanks for testing. No idea why transpose works.

The not test failure is a different error. Probably also one that only occurs randomly and only on OpenMPI, like the other three issues you opened. Not much we can do about these; OpenMPI just seems very unstable in Fedora right now.

**Comment by junghans** [comment]
Ok, the other one is just flacky and got fixed by re-triggering.
