### ISSUE TITLE
espresso-4.1.1: sigint fails on s390x (Fedora31)

### ISSUE THREAD

**Issue by junghans** [espressomd/espresso#3316]
Yet another issue:
```
 38/144 Test #133: sigint ............................................***Failed    3.18 sec
Fatal Python error: init_sys_streams: can't initialize sys standard streams
Traceback (most recent call last):
  File "/usr/lib64/python3.7/io.py", line 75, in <module>
    class RawIOBase(_io._RawIOBase, IOBase):
  File "/usr/lib64/python3.7/abc.py", line 126, in __new__
    cls = super().__new__(mcls, name, bases, namespace, **kwargs)
KeyboardInterrupt
F
======================================================================
FAIL: test_signal_handling (__main__.SigintTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/espresso/openmpi/testsuite/python/sigint.py", line 36, in test_signal_handling
    self.assertFalse(self.process.poll() is None)
AssertionError: True is not false
----------------------------------------------------------------------
Ran 1 test in 1.026s
FAILED (failures=1)
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:
  Process name: [[43748,1],0]
  Exit code:    1
--------------------------------------------------------------------------
```

Related: https://python-forum.io/Thread-Fatal-Python-error-init-sys-streams-can-t-initialize-sys-standard-streams-Attribute

Details [here](https://github.com/espressomd/espresso/files/3852800/build_s390x.log.txt)

**Comment by jngrad** [comment]
In a docker container with Fedora31 running with QEMU for s390x:
```
$ ./pypresso testsuite/python/sigint.py
.
----------------------------------------------------------------------
Ran 1 test in 1.010s

OK
```

Couldn't run any MPI-enabled test due to the following PMIX error:
```
$ mpirun --version
mpirun (Open MPI) 4.0.2
$ make -j24 check_unit_tests
      Start  1: RuntimeError_test
 1/68 Test  #1: RuntimeError_test ................   Passed    0.07 sec
      Start  2: RuntimeErrorCollector_test
 2/68 Test  #2: RuntimeErrorCollector_test .......***Failed    0.42 sec
[f18c49d4ba34:15077] PMIX ERROR: ERROR in file dstore_segment.c at line 110
[f18c49d4ba34:15077] PMIX ERROR: OUT-OF-RESOURCE in file gds_ds21_lock_pthread.c at line 176
[f18c49d4ba34:15077] *** Process received signal ***
[f18c49d4ba34:15077] Signal: Segmentation fault (11)
[f18c49d4ba34:15077] Signal code: Address not mapped (1)
[f18c49d4ba34:15077] Failing at address: (nil)
[f18c49d4ba34:15077] [ 0] [0x4001ba8860]
[f18c49d4ba34:15077] [ 1] /usr/lib64/pmix/mca_gds_ds21.so(+0x1ef0)[0x4001378ef0]
[f18c49d4ba34:15077] [ 2] /usr/lib64/pmix/mca_gds_ds21.so(+0x246e)[0x400137946e]
[f18c49d4ba34:15077] [ 3] /lib64/libmca_common_dstore.so.1(pmix_common_dstor_add_nspace+0x29a)[0x4001371eda]
[f18c49d4ba34:15077] [ 4] /lib64/libpmix.so.2(+0x4e98e)[0x400118e98e]
[f18c49d4ba34:15077] [ 5] /lib64/libevent-2.1.so.6(+0x276ec)[0x4000cc66ec]
[f18c49d4ba34:15077] [ 6] /lib64/libevent-2.1.so.6(event_base_loop+0x644)[0x4000cc6fd4]
[f18c49d4ba34:15077] [ 7] /lib64/libpmix.so.2(+0x7ee0e)[0x40011bee0e]
[f18c49d4ba34:15077] [ 8] /lib64/libpthread.so.0(+0x9ed6)[0x4000904ed6]
[f18c49d4ba34:15077] [ 9] /lib64/libc.so.6(+0x105e96)[0x4000a24e96]
[f18c49d4ba34:15077] [10] [0x0]
[f18c49d4ba34:15077] *** End of error message ***
```

**Comment by jngrad** [comment]
This issue is now obsolete, espresso-4.1.1 was replaced by espresso-4.1.2 ([koji build 1422305](https://koji.fedoraproject.org/koji/buildinfo?buildID=1422305)).
