### ISSUE TITLE
ESPResSo installation is broken (.so and .py name collision)

### ISSUE THREAD

**Issue by jngrad** [espressomd/espresso#3624]
https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/219704
```
   File "/builds/espressomd/espresso/build/testsuite/python/ek_eof_one_species_base.py", line 26, in <module>
1714     import espressomd.shapes
1715 ImportError: dynamic module does not define module export function (PyInit_shapes)
```
We currently install the compiled Cython files (.so), compiled libraries (.so) and Python files (.py) in the same folder, which is just asking for trouble. #3543 introduced a name collision between `shapes.py` and `shapes.so`. The waLBerla integration will pull in even more shared objects, increasing the likelihood of name collisions.

* We cannot rename `shapes.so` to `libshapes.so` because CMake already adds a `lib` prefix depending on the OS ([`add_library()` docs](https://cmake.org/cmake/help/v3.10/command/add_library.html#normal-libraries))
* Renaming the target to `EspressoShapes` leads to the following error:
  ```
  /home/espresso/espresso/src/core/grid_based_algorithms/lbboundaries/LBBoundary.hpp:25:10: fatal error: shapes/NoWhere.hpp: No such file or directory
   #include <shapes/NoWhere.hpp>
            ^~~~~~~~~~~~~~~~~~~~
  compilation terminated.
  ```
* Installing the target in a subfolder (e.g. `site-packages/espressomd/src/shapes.so`) leads to an import error:
  ```
  >>> import espressomd.shapes
  Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "/tmp/espresso-unit-tests/lib/python3.6/site-packages/espressomd/__init__.py", line 23, in <module>
      from . import _init
    File "_init.pyx", line 20, in init espressomd._init
  ImportError: shapes.so: cannot open shared object file: No such file or directory
  ```

**Comment by jngrad** [comment]
If I understand [walberla/walberla:cmake/waLBerlaModuleDependencySystem.cmake](https://i10git.cs.fau.de/walberla/walberla/-/blob/ff2f5e13816be1547f69b487f9aaed4481094f06/cmake/waLBerlaModuleDependencySystem.cmake) correctly, in waLBerla target names are generated automatically from the filepath relative to `${CMAKE_ROOT}`, with slashes replaced by minuses, to avoid collisions. This makes the CMake logic a little bit more cumbersome, though.
