### ISSUE TITLE
Rotational diffusion test fails with Brownian Dynamics

### ISSUE THREAD

**Issue by jngrad** [espressomd/espresso#3875]
Test `rotational-diffusion-aniso` has a bad feature guard. Fixing the guard (d02b835b) reveals the test doesn't pass:
```
FAIL: test_case_10 (__main__.RotDiffAniso)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/ssd/jgrad/espresso-fork-PR/build-seraue-release/testsuite/python/rotational-diffusion-aniso.py", line 383, in test_case_10
    self.check_rot_diffusion(n)
  File "/ssd/jgrad/espresso-fork-PR/build-seraue-release/testsuite/python/rotational-diffusion-aniso.py", line 327, in check_rot_diffusion
    'diffusion is too large: {1}'.format(j, dcosjj_dev[j]))
AssertionError: 1.0 not less than or equal to 0.2 : Relative deviation dcosjj_dev[0] in a rotational diffusion is too large: 1.0
```

**Comment by jngrad** [comment]
The underlying issue is a regression introduced by be3e2f399c72c. Here is the fix:
```diff
diff --git a/src/core/thermostats/brownian_inline.hpp b/src/core/thermostats/brownian_inline.hpp
index ec76b9552..f3ed6af7f 100644
--- a/src/core/thermostats/brownian_inline.hpp
+++ b/src/core/thermostats/brownian_inline.hpp
@@ -351,5 +351,5 @@ bd_drag_rot(Thermostat::GammaType const &brownian_gamma_rotation, Particle &p,
     return local_rotate_particle_body(p, dphi_u, dphi_m);
   }
-  return {};
+  return p.r.quat;
 }
 
@@ -463,5 +463,5 @@ bd_random_walk_rot(BrownianThermostat const &brownian, Particle const &p,
     return local_rotate_particle_body(p, dphi_u, dphi_m);
   }
-  return {};
+  return p.r.quat;
 }
 
```
