### ISSUE TITLE
CUDA 11 incompatible with GCC 10.2 and Clang 10.0

### ISSUE THREAD

**Issue by jngrad** [espressomd/espresso#4081]
```
In file included from <built-in>:1:
In file included from /usr/local/cuda/include/cuda_runtime.h:83:
/usr/local/cuda/include/crt/host_config.h:147:2: error: -- unsupported clang version! clang version must be
less than 10 and greater than 3.2 . The nvcc flag '-allow-unsupported-compiler' can be used to override this
version check; however, using an unsupported host compiler may cause compilation failure or incorrect run
time execution. Use at your own risk.
```

GCC 10.2 header files are incompatible with NVCC 11: adding `-allow-unsupported-compiler` to the NVCC compiler flags leads to the following error:
```
/usr/include/c++/10/type_traits(1396): error: type name is not allowed
/usr/include/c++/10/type_traits(1396): error: identifier "__is_same_as" is undefined
/usr/include/c++/10/type_traits(3182): error: type name is not allowed
/usr/include/c++/10/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list
            argument types are: (const long, std::is_same<signed int, signed int>)
    detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...),
                                      const char *, const _CharT *, std::size_t *, _Base...)
                                      [with _TRet=long, _Ret=int, _CharT=char, _Base=<int>]" 
/usr/include/c++/10/bits/basic_string.h(6547): here
```

Clang 10.0 incorrectly detects CUDA 11 as CUDA 7.0. Creating a new file `/usr/local/cuda/version.txt` containing the string `CUDA Version 11.0.221` (obtained from `nvcc --version`) doesn't help: `clang++-10 --verbose` prints CUDA 10.1. CUDA source files fail to compile with the following error:
```
clang: warning: Unknown CUDA version 11.0. Assuming the latest supported version 10.1 [-Wunknown-cuda-version]
In file included from /usr/local/cuda-11.0/include/thrust/system/cuda/detail/parallel_for.h:36:
/usr/local/cuda-11.0/include/thrust/system/cuda/detail/core/agent_launcher.h:576:11: error: use of undeclared identifier 'va_printf'
          _CubLog("Invoking %s<<<%u, %d, %d, %lld>>>(), %d items per thread, %d SM occupancy, %d vshmem size, %d ptx_version\n",
          ^
/usr/local/cuda-11.0/include/cub/util_debug.cuh:151:42: note: expanded from macro '_CubLog'
            #define _CubLog(format, ...) va_printf("[block (%d,%d,%d), thread (%d,%d,%d)]: " format, __VA_ARGS__);
                                         ^
2 errors generated when compiling for sm_52.
```
I didn't check for Clang 11, since [`nvidia/cuda`](https://hub.docker.com/r/nvidia/cuda/tags) Docker images are only released for LTS versions of Ubuntu; Clang 11 is currently only available for a non-LTS version (Ubuntu 20.10). Clang-9 doesn't recognize CUDA 11.

**Comment by RudolfWeeber** [comment]
Are you sure about clang-11 not being available on 20.04. I could `apt install` it on my ICP machine.

**Comment by RudolfWeeber** [comment]
Cuda 11.2 and gcc-10.2 (as provided by spack) play nice.

**Comment by mkuron** [comment]
Officially, GCC 10 is not supported even by the latest CUDA (https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html), though according to https://gist.github.com/ax3l/9489132#nvcc, CUDA 11.1 supports it.
Clang 11 (when used in place of nvcc) supports CUDA 11 according to https://gist.github.com/ax3l/9489132#clang--x-cuda.

**Comment by jngrad** [comment]
* Clang 11 is available in `focal-updates`, but it doesn't correctly detect CUDA 11.0 and 11.1 (e.g. cannot find `CUDA_LIBRARY`)
* CUDA 11.2 doesn't have a docker image yet
* CUDA 11.1 compiles GCC 10.2 (couldn't run the binaries, the nvidia driver on icp machines is for CUDA 11.0)
* CUDA 11.0 doesn't support GCC 10.2

**Comment by jngrad** [comment]
* CUDA 11.2 now has a docker image
* CUDA 11.2 supports GCC 10.2
* Clang 11 doesn't correctly detect CUDA 11.2

**Comment by jngrad** [comment]
ESPResSo 4.2-dev compiled with GCC 10.2 in the CUDA 11.2.0 docker image fails during the call to `exit()`. GDB backtrace:
```
#0  0x00007fb2ed3ba762 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x00007fb2ed983eb5 in thrust::cuda_cub::throw_on_error (msg=0x7fb2edc9ba60 "get_max_shared_memory_per_block :failed to cudaGetDevice", 
    status=cudaErrorCudartUnloading) at /usr/local/cuda/include/thrust/system/detail/system_error.inl:65
#2  thrust::cuda_cub::core::get_max_shared_memory_per_block () at /usr/local/cuda/include/thrust/system/cuda/detail/core/util.h:487
#3  thrust::cuda_cub::core::AgentLauncher<thrust::cuda_cub::__parallel_for::ParallelForAgent<thrust::cuda_cub::for_each_f<thrust::device_ptr<CUDA_particle_data>, thrust::detail::wrapped_function<thrust::detail::allocator_traits_detail::gozer, void> >, long> >::AgentLauncher<long>
    (debug_sync_=false, name_=<synthetic pointer>, stream_=0x1, count_=<optimized out>, plan_=..., this=<synthetic pointer>)
    at /usr/local/cuda/include/thrust/system/cuda/detail/core/agent_launcher.h:406
#4  thrust::cuda_cub::__parallel_for::parallel_for<thrust::cuda_cub::for_each_f<thrust::device_ptr<CUDA_particle_data>, thrust::detail::wrapped_function<thrust::detail::allocator_traits_detail::gozer, void> >, long> (stream=0x1, f=..., num_items=<optimized out>)
    at /usr/local/cuda/include/thrust/system/cuda/detail/parallel_for.h:140
#5  thrust::cuda_cub::parallel_for<thrust::cuda_cub::tag, thrust::cuda_cub::for_each_f<thrust::device_ptr<CUDA_particle_data>, thrust::detail::wrapped_function<thrust::detail::allocator_traits_detail::gozer, void> >, long> (f=..., policy=..., f=..., count=<optimized out>)
    at /usr/local/cuda/include/thrust/system/cuda/detail/parallel_for.h:163
#6  thrust::cuda_cub::for_each_n<thrust::cuda_cub::tag, thrust::device_ptr<CUDA_particle_data>, long, thrust::detail::allocator_traits_detail::gozer> (op=..., count=<optimized out>, first=..., policy=...) at /usr/local/cuda/include/thrust/system/cuda/detail/for_each.h:80
#7  thrust::for_each_n<thrust::cuda_cub::tag, thrust::device_ptr<CUDA_particle_data>, long, thrust::detail::allocator_traits_detail::gozer>
    (first=..., n=<optimized out>, f=..., exec=...) at /usr/local/cuda/include/thrust/detail/for_each.inl:71
#8  0x00007fb2edb9a3f9 in thrust::detail::allocator_traits_detail::destroy_range<CudaDeviceAllocator<CUDA_particle_data>, thrust::device_ptr<CUDA_particle_data>, long> (n=<optimized out>, p=..., a=...) at /usr/local/cuda/include/thrust/detail/allocator/destroy_range.inl:135
#9  thrust::detail::destroy_range<CudaDeviceAllocator<CUDA_particle_data>, thrust::device_ptr<CUDA_particle_data>, long> (
    n=<optimized out>, p=..., a=...) at /usr/local/cuda/include/thrust/detail/allocator/destroy_range.inl:158
#10 thrust::detail::contiguous_storage<CUDA_particle_data, CudaDeviceAllocator<CUDA_particle_data> >::destroy (last=..., first=..., 
    this=0x7fb2ee1fac20 <particle_data_device>) at /usr/local/cuda/include/thrust/detail/contiguous_storage.inl:317
#11 thrust::detail::vector_base<CUDA_particle_data, CudaDeviceAllocator<CUDA_particle_data> >::~vector_base (
    this=0x7fb2ee1fac20 <particle_data_device>, __in_chrg=<optimized out>) at /usr/local/cuda/include/thrust/detail/vector_base.inl:561
#12 thrust::device_vector<CUDA_particle_data, CudaDeviceAllocator<CUDA_particle_data> >::~device_vector (
    this=0x7fb2ee1fac20 <particle_data_device>, __in_chrg=<optimized out>) at /usr/local/cuda/include/thrust/device_vector.h:84
#13 0x00007fb2f04ada27 in ?? () from /usr/lib/x86_64-linux-gnu/libc.so.6
#14 0x00007fb2f04adbe0 in exit () from /usr/lib/x86_64-linux-gnu/libc.so.6
#15 0x00007fb2f048b0ba in __libc_start_main () from /usr/lib/x86_64-linux-gnu/libc.so.6
#16 0x00000000005fa4de in _start ()
```
This is caused by the following 3 global variables (re-order them to get a different type `T` in the backtrace):
https://github.com/espressomd/espresso/blob/6880e6c3c3cb16cf0800cfb8c347a4079abcdc02/src/core/cuda_common_cuda.cu#L54-L59

Removing the `static` keyword didn't help. Using `.resize(n)` instead of the workaround in [`resize_or_replace()`](https://github.com/espressomd/espresso/blob/6880e6c3c3cb16cf0800cfb8c347a4079abcdc02/src/core/cuda_common_cuda.cu#L89-L110) didn't help. 
The exception is thrown when the python script involves these global variables, e.g. `testsuite/python/save_checkpoint_ek.gpu_1.py`.
