### ISSUE TITLE
Installation instructions for MacPorts...

### ISSUE THREAD

**Issue by bindgens1** [espressomd/espresso#4258]
... should include `py37-scipy`

The software can be build without scipy but the import fails

```
Python 3.8.10 (default, May  7 2021, 19:12:42)
[Clang 12.0.5 (clang-1205.0.22.9)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import espressomd as md
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sebastian/git/espresso/build/src/python/espressomd/__init__.py", line 25, in <module>
    from .system import System
  File "system.pyx", line 37, in init espressomd.system
  File "analyze.pyx", line 29, in init espressomd.analyze
ModuleNotFoundError: No module named 'scipy'
```

**Comment by bindgens1** [comment]
Further information:
I built with py38 instead of py37, so maybe there are some changed dependencies.

**Comment by jngrad** [comment]
This also needs to be added to the [Ubuntu 20.04 section](https://espressomd.github.io/doc/installation.html#installing-requirements-on-ubuntu-linux).

**Comment by KaiSzuttor** [comment]
or we could provide a macports package...
