### ISSUE TITLE
Walberla: LBFluidNodeWalberla unexpected behavior for negative indices

### ISSUE THREAD

**Issue by reinaual** [espressomd/espresso#4425]
Currently the `__getitem__` access to the `LBFluidWalberla` works properly for `LBFluidSliceWalberla` but has some missing convenience options for the plain `LBFluidNodeWalberla` case.
Im not sure what the optimal solution is, maybe it is as simple as "adding" the field shape to negative indices.

```python
import espressomd
import espressomd.lb

system = espressomd.System(box_l=[10, 10, 10])
system.time_step = 1.0

lattice = espressomd.lb.LatticeWalberla(n_ghost_layers=1, agrid=1.0)

lbf = espressomd.lb.LBFluidWalberla(lattice=lattice, viscosity=1.0, density=1.0, tau=1.0)

print(lbf[-1, -1, -1].density)
```

```
ERROR: FluidNodeWalberla failed: Index error
Traceback (most recent call last):
  File "../script/lb_issue.py", line 11, in <module>
    print(lbf[-1, -1, -1].density)
  File "/ssd/areinauer/espresso/rudolf/build/src/python/espressomd/lb.py", line 495, in __getitem__
    return LBFluidNodeWalberla(lb_sip=self, index=np.array(key))
  File "/ssd/areinauer/espresso/rudolf/build/src/python/espressomd/lb.py", line 662, in __init__
    utils.handle_errors("LBFluidNode instantiation failed")
  File "utils.pyx", line 238, in espressomd.utils.handle_errors
  File "utils.pyx", line 257, in espressomd.utils.handle_errors
Exception: LBFluidNode instantiation failed: ERROR: FluidNodeWalberla failed: Index error
```

**Comment by jngrad** [comment]
The LB and EK classes for slices and nodes were merged into common base classes to get all the fancy options:
- a LB node can now be accessed via negative indices (feature taken from the EK code)
- an EK node can be equality-compared to another EK node (feature taken from the LB code)
