### ISSUE TITLE
error: -- unsupported clang version! clang version must be less than 13 and greater than 3.2 

### ISSUE THREAD

**Issue by sonukr234** [espressomd/espresso#4574]
```
┌──(excalibur㉿Excalibur-PC)-[~/Pyrit/modules/cpyrit_cuda]
└─$ python2 setup.py build
The CUDA compiler and headers required to build kernel were not found. Trying to continue anyway...
running build
running build_ext
Compiling CUDA module using nvcc 11.4, V11.4.152
Build cuda_11.4.r11.4/compiler.30521435_0...
Executing 'nvcc -m64 -ccbin clang -Xcompiler "-fPIC" --ptx ./_cpyrit_cudakernel.cu'
In file included from <built-in>:1:
In file included from /usr/include/cuda_runtime.h:83:
/usr/include/crt/host_config.h:147:2: error: -- unsupported clang version! clang version must be less than 13 and greater than 3.2 . The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.
#error -- unsupported clang version! clang version must be less than 13 and greater than 3.2 . The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.
 ^
1 error generated.
Traceback (most recent call last):
  File "setup.py", line 166, in <module>
    setup(**setup_args)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
    self.run_command(cmd_name)
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
└─$ cdccccxx
    subprocess.check_call(nvcc_cmd, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'nvcc -m64 -ccbin clang -Xcompiler "-fPIC" --ptx ./_cpyrit_cudakernel.cu' returned non-zero exit status 1

┌──(excalibur㉿Excalibur-PC)-[~/Pyrit/modules/cpyrit_cuda]
└─$ ls
COPYING  _cpyrit_cuda.c  _cpyrit_cuda.h  _cpyrit_cudakernel.cu  MANIFEST.in  setup.py

┌──(excalibur㉿Excalibur-PC)-[~/Pyrit/modules/cpyrit_cuda]
└─$ clang --v
clang: err
clang: error: no input files

┌──(excalibur㉿Excalibur-PC)-[~/Pyrit/modules/cpyrit_cuda]
└─$ clang -v
Debian clang version 14.0.6-2
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/10
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/11
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/12
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/12
Candidate multilib: .;@m64
Selected multilib: .;@m64
```

**Comment by jngrad** [comment]
Hi! Did you mean to open a ticket on the [JPaulMora/Pyrit](https://github.com/JPaulMora/Pyrit) project? We can only offer support for ESPResSo.

From my experience with ESPResSo, CUDA 11.4 is almost fully supported by Clang 12, which is available on `sid`:
```sh
clang++-12 -Wno-unknown-cuda-version --cuda-gpu-arch=sm_75 -std=c++14 kernel.cu
```
